### ISSUE TITLE
Trouble connecting to UR5 (trying ur_driver and ur_modern_driver)

### ISSUE THREAD

**Issue by AlisonBarnes** [ThomasTimm/ur_modern_driver#102]
Hi, 

Sorry, very new at this, having some issues connecting through to our UR5  @robot.Chunting @ThomasTimm , it looks like you solved this in issue 51, but unsure what you did...

I'm not on wifi, have laptop connected to UR_5, but also running Ubuntu inside a VirtualBox, we've set up bridged adaptor between VB and PC and I can ping robot...

I have tried ur_driver and ur_modern_driver, output form each below...

Thanks
Ali

Trying:

roslaunch ur_modern_driver ur5_bringup.launch robot_ip:=10.0.0.10

I get this:
datascience4@datascience4-VirtualBox:~$ roslaunch ur_modern_driver ur5_bringup.launch robot_ip:=10.0.0.10
... logging to /home/datascience4/.ros/log/5353868e-1b63-11e7-a9d3-080027d987ef/roslaunch-datascience4-VirtualBox-8512.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

redefining global property: pi
when processing file: /home/datascience4/universal_robot_ws/src/universal_robot/ur_description/urdf/ur5.urdf.xacro
included from: /home/datascience4/universal_robot_ws/src/universal_robot/ur_description/urdf/ur5_robot.urdf.xacro
started roslaunch server http://datascience4-VirtualBox:40601/

SUMMARY
========

PARAMETERS
 * /robot_description: <?xml version="1....
 * /rosdistro: indigo
 * /rosversion: 1.11.21
 * /ur_driver/base_frame: base
 * /ur_driver/max_payload: 5.0
 * /ur_driver/max_velocity: 10.0
 * /ur_driver/min_payload: 0.0
 * /ur_driver/prefix: 
 * /ur_driver/robot_ip_address: 10.0.0.10
 * /ur_driver/servoj_time: 0.008
 * /ur_driver/tool_frame: tool0_controller

NODES
  /
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    ur_driver (ur_modern_driver/ur_driver)

auto-starting new master
process[master]: started with pid [8527]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 5353868e-1b63-11e7-a9d3-080027d987ef
process[rosout-1]: started with pid [8540]
started core service [/rosout]
process[robot_state_publisher-2]: started with pid [8551]
process[ur_driver-3]: started with pid [8556]
[FATAL] [1491550035.285923290]: Error connecting to get firmware version
terminate called after throwing an instance of 'std::system_error'
  what():  Invalid argument
[ur_driver-3] process has died [pid 8556, exit code -6, cmd /home/datascience4/universal_robot_ws/devel/lib/ur_modern_driver/ur_driver __name:=ur_driver __log:=/home/datascience4/.ros/log/5353868e-1b63-11e7-a9d3-080027d987ef/ur_driver-3.log].
log file: /home/datascience4/.ros/log/5353868e-1b63-11e7-a9d3-080027d987ef/ur_driver-3*.log

Trying:
roslaunch ur_bringup ur5_bringup.launch robot_ip:=10.0.0.10

datascience4@datascience4-VirtualBox:~$ roslaunch ur_bringup ur5_bringup.launch robot_ip:=10.0.0.10
... logging to /home/datascience4/.ros/log/edd9a804-1b64-11e7-a7e9-080027d987ef/roslaunch-datascience4-VirtualBox-8748.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

redefining global property: pi
when processing file: /home/datascience4/universal_robot_ws/src/universal_robot/ur_description/urdf/ur5.urdf.xacro
included from: /home/datascience4/universal_robot_ws/src/universal_robot/ur_description/urdf/ur5_robot.urdf.xacro
started roslaunch server http://datascience4-VirtualBox:44128/

SUMMARY
========

PARAMETERS
 * /robot_description: <?xml version="1....
 * /robot_ip_address: 10.0.0.10
 * /robot_reverse_port: 50001
 * /rosdistro: indigo
 * /rosversion: 1.11.21
 * /tf2_buffer_server/buffer_size: 120.0
 * /ur_driver/max_payload: 10.0
 * /ur_driver/max_velocity: 10.0
 * /ur_driver/min_payload: 0.0
 * /ur_driver/prefix: 

NODES
  /
    robot_state_publisher (robot_state_publisher/state_publisher)
    tf2_buffer_server (tf2_ros/buffer_server)
    ur_driver (ur_driver/driver.py)

auto-starting new master
process[master]: started with pid [8763]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to edd9a804-1b64-11e7-a7e9-080027d987ef
process[rosout-1]: started with pid [8776]
started core service [/rosout]
process[robot_state_publisher-2]: started with pid [8787]
process[ur_driver-3]: started with pid [8790]
process[tf2_buffer_server-4]: started with pid [8795]
Setting prefix to 
[WARN] [WallTime: 1491550597.251437] No calibration offset for joint "shoulder_pan_joint"
[WARN] [WallTime: 1491550597.251699] No calibration offset for joint "shoulder_lift_joint"
[WARN] [WallTime: 1491550597.251881] No calibration offset for joint "elbow_joint"
[WARN] [WallTime: 1491550597.252052] No calibration offset for joint "wrist_1_joint"
[WARN] [WallTime: 1491550597.252218] No calibration offset for joint "wrist_2_joint"
[WARN] [WallTime: 1491550597.252383] No calibration offset for joint "wrist_3_joint"
[INFO] [WallTime: 1491550597.252569] No calibration offsets loaded from urdf
[INFO] [WallTime: 1491550597.254961] Max velocity accepted by ur_driver: 10.0 [rad/s]
[INFO] [WallTime: 1491550597.258292] Bounds for Payload: [0.0, 10.0]
Traceback (most recent call last):
  File "/home/datascience4/universal_robot_ws/src/universal_robot/ur_driver/src/ur_driver/driver.py", line 1018, in <module>
    if __name__ == '__main__': main()
  File "/home/datascience4/universal_robot_ws/src/universal_robot/ur_driver/src/ur_driver/driver.py", line 945, in main
    program = fin.read() % {"driver_hostname": get_my_ip(robot_hostname, PORT), "driver_reverseport": reverse_port}
  File "/home/datascience4/universal_robot_ws/src/universal_robot/ur_driver/src/ur_driver/driver.py", line 854, in get_my_ip
    s = socket.create_connection((robot_ip, port))
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
socket.error: [Errno 110] Connection timed out
[ur_driver-3] process has died [pid 8790, exit code 1, cmd /home/datascience4/universal_robot_ws/src/universal_robot/ur_driver/src/ur_driver/driver.py 10.0.0.10 50001 __name:=ur_driver __log:=/home/datascience4/.ros/log/edd9a804-1b64-11e7-a7e9-080027d987ef/ur_driver-3.log].
log file: /home/datascience4/.ros/log/edd9a804-1b64-11e7-a7e9-080027d987ef/ur_driver-3*.log

**Comment by ThomasTimm** [comment]
In both cases, it seems like the driver cannot connect to the robot.
Seeing that you can actually ping the robot, I don't know what the problem is, other than it is related to your (network) setup and not the driver.
My only recommendation, and I say this to everybody, is to not use a VM for doing network-based control of hardware. It is impossible to control your network interface, when the host OS, which is running the VM, can override the network interface at any time. You can use any old computer, or even a Raspberry Pi or Odroid, and install Ubuntu on that, if you don't feel like setting up dual-boot on your main computer.

To test that the driver works within your VM, you can try and install the robot simulator from Universal Robot ( https://www.universal-robots.com/download/?option=26264#section16632 ), and then connect using your VM's IP address once the simulator is running. But if you ever want to control a physical robot, you need to ditch your VM.
