### ISSUE TITLE
UR5 Robot not simulating in Gazebo

### ISSUE THREAD

**Issue by AlisonBarnes** [ThomasTimm/ur_modern_driver#106]
We have used ur_modern_driver to move our UR5 robot in real life. However we have a major hurdle with our development, that we can not get the UR5 robot to move in the simulator(GAZEBO) without the use of MoveIt. 

We have tried many alternatives without much luck. does anybody know how we can get the UR5 robot to move from a python script or c++ without using MoveIt by directly calling the rostopics of the UR5 robot.

Examples would be greatly appreciated. We are using Ubuntu 14.04 and Indigo

thanks
Anthony Biviano

**Comment by ThomasTimm** [comment]
Try looking in the test_move.py script...
