### ISSUE TITLE
Support for UR 5.0 (beta?) system software

### ISSUE THREAD

**Issue by Eirtrand** [ThomasTimm/ur_modern_driver#131]
Im using the new 5.0 URSoftware with ROS. The driver comunicates with the robot, but Im not able to controll it using URScript, test_move.py or moveIt. TF, joint states and everyting else works fine. I get no errors when trying to move the robot, its just stuck on "on_goal" forever.

**Comment by gavanderhoorn** [comment]
I'm probably being dense, but what is the `5.0 driver`?

**Comment by Eirtrand** [comment]
I meant the URSoftware version 5.0.0.0.0, its a beta software that my ur3 came with. It uses PolyScope 1.0.192.0.0.0 and URControl 1.0.141.0.0.0

**Comment by gavanderhoorn** [comment]
Adding support for new system software versions will require publicly available information from Universal Robots.

I suggest you ask UR support to update their documentation on the *client interface* (article 16496).

**Comment by gavanderhoorn** [comment]
Could you tell us what the conclusion is / was?

**Comment by Eirtrand** [comment]
I didnt have time to look into it, lets hope they make it available soon.

**Comment by gavanderhoorn** [comment]
Seems to have taken some time, but `v5` is out (or at least the manuals): [Software_Manual_en_Global.pdf](https://s3-eu-west-1.amazonaws.com/ur-support-site/41109/Software_Manual_en_Global.pdf).
