### ISSUE TITLE
UR3 breaking/wobbling problem

### ISSUE THREAD

**Issue by htugal** [ThomasTimm/ur_modern_driver#137]
Hi, 
In order to control robot, I publish the ur_driver/joint_speed based on some calculations and the robot subscribes it, yet  robot occasionally breaks for a really short period of time and continues to operate normally. I am not sure whether it actually breaks or not but the smooth movements interrupted like a breaking/wobbling behaviour. Frequency of this breaking behaviour looks random, couldn't find any relationship with anything and running out of options..

I  wonder whether   anybody  has ever come cross such behaviour in UR3 or not ?

**Comment by happygaoxiao** [comment]
I have also come cross this behavior. There are some zero value of joint speed as issuse [#139](https://github.com/ThomasTimm/ur_modern_driver/issues/139)

**Comment by htugal** [comment]
Hi,
I thought that might be due to package loss/drop within the network communication, yet same behaviours appear even if I use a port switch, here is the first three joints ref and actual velocities: #139 

![screenshot from 2017-10-13 15 38 50](https://user-images.githubusercontent.com/30143964/31551554-d6ea4e3e-b02c-11e7-94cb-2625c9ce2d5b.png)

**Comment by gavanderhoorn** [comment]
Even though #139 was reported later, I believe it is a similar enough issue to suggest we continue trying to diagnose it there, and close this one.

I see you've already commented on #139 as well @htugal.
