### ISSUE TITLE
get_inverse_kin;ur5 script manual

### ISSUE THREAD

**Issue by JiangtaoYin** [ThomasTimm/ur_modern_driver#144]
hello,
     I am trying to control ur5 running through a trajectory in windows. I want to use the script function：`servoj() `, but my data format is based on the tool space(a vector:X,Y,Z,RX,RY,RZ), so I need to translate the data to joint space. Followed my script code: 
    ```
def trajPlan():
 get_inverse_kin([0.55718 -0.04416 0.45048 -0.95300 1.49430 -0.60280]) = cmd_servo_q
 servoj([cmd_servo_q],t=2)
end
```
At [(http://www.sysaxes.com/manuels/scriptmanual_en_3.1.pdf)]
i found the ur5 script manual,
 and one of the functions that i can give is called get_inverse_kin(). if i have a c++ program 
running on an external pc, and i send this command to the ur5 to get the joint position, 
then try to use the servoj to servo ur5 with the joint position. but the robot had no response.

I hope someone will be able to  @help,ThomasTimm
Tom

**Comment by gavanderhoorn** [comment]
I'm sorry, but your issue doesn't appear to be about the `ur_modern_driver` package.

As this issue tracker is for that package alone, I'm going to close your issue.

If you're not ok with that, please re-open and clarify your OP.
