### ISSUE TITLE
Controller error trying to interface with CB3/3.40/UR3

### ISSUE THREAD

**Issue by naijoug** [ThomasTimm/ur_modern_driver#150]
I use moveit control UR3 real. When planning distance is far, the robot will stop. PolyScope show the error info:

```
Runtime error: The program used too much time without instructing the robot what
to do. Consider using a Wait or sync() to split long program sequences that do not
move the robot.
```

**Comment by gavanderhoorn** [comment]
I believe we don't support version `3.4.x` yet. See also #147.

Can you please comment on that issue?
