### ISSUE TITLE
Controlling UR5 with depth sensor ??

### ISSUE THREAD

**Issue by Abduoit** [ThomasTimm/ur_modern_driver#159]
Hi

Is there anyway to control ur5 with depth camera ?

**Comment by gavanderhoorn** [comment]
Not without some intermediate steps (ie: interpreting point clouds / depth images and coming up with actuation commands).

I would actually recommend you ask this over at [ROS Answers](http://answers.ros.org/).

This is really an issue tracker, for reporting issues with the package(s) in this repository.
