### ISSUE TITLE
How to control the joints separately ??

### ISSUE THREAD

**Issue by Abduoit** [ThomasTimm/ur_modern_driver#160]
Hi 

Thanks for your great effort, I cloned this repo and I tested it with real ur5 arm, everything works fine with gazebo, rviz and moveit.

BUT I want to know how to control the joints individually, 
for example, I publish the joints position, I know it's something like 

`rostopic pub /arm_controller/state control_msgs/JointTrajectoryControllerState '{{position: {0.0, 0.0, 0.0, 1.0, 6.0, 0.0}}'`

but I don't know exactly, can u plz help me ?

**Comment by gavanderhoorn** [comment]
I'm sorry to hear you're having trouble getting this to work, but this issue tracker is not the place to ask such generic questions. I suggest you open a question on ROS Answers.

I can say that `JointTrajectoryControllerState` is not a message that you can use to control a robot. It's status message that is used by controllers to broadcast their state.
