### ISSUE TITLE
Compiling for OSX Sierra

### ISSUE THREAD

**Issue by keshavchintamani** [ThomasTimm/ur_modern_driver#167]
Hi, 

I've managed to compile all dependencies (phew!) from source for this driver on my Macbook including:

1. ros-desktop-full
2. moveit
3. ros_control 

I thought I had reached my goal until I hit this roadblock which I cant get around.

```
[100%] Linking CXX shared library /Users/sandbox/roskinetic_ws/universalrobots_ws/devel/lib/libur_hardware_interface.dylib
Undefined symbols for architecture x86_64:
  "RobotStateRT::getIActual()", referenced from:
      ros_control_ur::UrHardwareInterface::read() in ur_hardware_interface.cpp.o
  "RobotStateRT::getQActual()", referenced from:
      ros_control_ur::UrHardwareInterface::read() in ur_hardware_interface.cpp.o
  "RobotStateRT::getQdActual()", referenced from:
      ros_control_ur::UrHardwareInterface::read() in ur_hardware_interface.cpp.o
  "RobotStateRT::getTcpForce()", referenced from:
      ros_control_ur::UrHardwareInterface::read() in ur_hardware_interface.cpp.o
  "UrDriver::closeServo(std::__1::vector<double, std::__1::allocator<double> >)", referenced from:
      ros_control_ur::UrHardwareInterface::doSwitch(std::__1::list<hardware_interface::ControllerInfo, std::__1::allocator<hardware_interface::ControllerInfo> > const&, std::__1::list<hardware_interface::ControllerInfo, std::__1::allocator<hardware_interface::ControllerInfo> > const&) in ur_hardware_interface.cpp.o
  "UrDriver::uploadProg()", referenced from:
      ros_control_ur::UrHardwareInterface::doSwitch(std::__1::list<hardware_interface::ControllerInfo, std::__1::allocator<hardware_interface::ControllerInfo> > const&, std::__1::list<hardware_interface::ControllerInfo, std::__1::allocator<hardware_interface::ControllerInfo> > const&) in ur_hardware_interface.cpp.o
  "UrDriver::servoj(std::__1::vector<double, std::__1::allocator<double> >, int)", referenced from:
      ros_control_ur::UrHardwareInterface::write() in ur_hardware_interface.cpp.o
  "UrDriver::setSpeed(double, double, double, double, double, double, double)", referenced from:
      ros_control_ur::UrHardwareInterface::write() in ur_hardware_interface.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [ur_modern_driver/CMakeFiles/ur_hardware_interface.dir/build.make:128: /Users/sandbox/roskinetic_ws/universalrobots_ws/devel/lib/libur_hardware_interface.dylib] Error 1
make[1]: *** [CMakeFiles/Makefile2:1192: ur_modern_driver/CMakeFiles/ur_hardware_interface.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
Invoking "make -j4 -l4" failed
```

All symbols are this seems internal to ur_modern_driver and my ROS_PACKAGE_PATH looks ok.  I'm running:
Apple LLVM version 8.1.0 (clang-802.0.42)
cmake version 3.10.2
GNU Make 4.2.1

Any help/thoughts would be much appreciated!

**Comment by gavanderhoorn** [comment]
I'm not a Mac user, so I can't really help you.

The only thing that touches anything that I could think of could  be of influence here could be this:

https://github.com/ThomasTimm/ur_modern_driver/blob/9397f47ac158fe5976719f33101334371bc15d44/CMakeLists.txt#L121-L131

This doesn't seem to cater for clang specifically and I seem to remember that clang needed some additional flags as well. This may not be the case any more, but I thought I'd mention it.

Note that ROS on OSX these days is far from easy to setup. You found that out already, but it may also influence your chances of finding support for this particular combination of things.

**Comment by keshavchintamani** [comment]
@gavanderhoorn Thanks! I'm so close to this it seems a shame to give up!  I'm suspecting the same issue, i.e CMake is unable to load the right standard library. All missing symbols start with these references to the stdlib:
UrDriver::servoj(std::__1::vector<double, std::__1::allocator<double> >, int)", referenced from:

but I've tried 
set(CMAKE_CXX_FLAGS "-std=c++11 -stdlib=libc++ -g3 -Wall -O0")
set(CMAKE_REQUIRED_LIBRARIES "-lc++")
set(CMAKE_EXE_LINKER_FLAGS "-stdlib=libc++")

in different combinations but it doesnt seem to make a difference.

**Comment by gavanderhoorn** [comment]
Well, as I've written above, I'm not an OSX user, so I really can't help you.

**Comment by horagong** [comment]
@keshavchintamani Hi, I read you mail lately.

I think this change would be helpful.

* for Undefined symbols for architecture x86_64:
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index f4b01d1..862a701 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -111,7 +111,7 @@ catkin_package(
   INCLUDE_DIRS include
 #  LIBRARIES ur_modern_driver
   CATKIN_DEPENDS hardware_interface controller_manager actionlib control_msgs geometry_msgs roscpp sensor_msgs trajectory_msgs ur_msgs
-  DEPENDS ur_hardware_interface
+#  DEPENDS ur_hardware_interface
 )

 ###########
@@ -140,7 +140,7 @@ include_directories(include
 ## Declare a C++ library

 # Hardware Interface
-add_library(ur_hardware_interface src/ur_hardware_interface.cpp)
+add_library(ur_hardware_interface src/ur_hardware_interface.cpp src/ur_driver.cpp src/ur_realtime_communication.cpp src/ur_communication.cpp src/robot_state.cpp src/robot_state_RT.cpp src/do_output.cpp) 
 target_link_libraries(ur_hardware_interface
   ${catkin_LIBRARIES}
 )
```
* for undefined symbol: be64toh(x), mac has no those macro so you need some definitions for it.
```
#ifndef PORTABLE_ENDIAN_H_
#define PORTABLE_ENDIAN_H_
#ifdef __APPLE__ 
#include <machine/endian.h>
#include <libkern/OSByteOrder.h>

#define htobe16(x) OSSwapHostToBigInt16(x)
#define htole16(x) OSSwapHostToLittleInt16(x)
#define be16toh(x) OSSwapBigToHostInt16(x)
#define le16toh(x) OSSwapLittleToHostInt16(x)

#define htobe32(x) OSSwapHostToBigInt32(x)
#define htole32(x) OSSwapHostToLittleInt32(x)
#define be32toh(x) OSSwapBigToHostInt32(x)
#define le32toh(x) OSSwapLittleToHostInt32(x)

#define htobe64(x) OSSwapHostToBigInt64(x)
#define htole64(x) OSSwapHostToLittleInt64(x)
#define be64toh(x) OSSwapBigToHostInt64(x)
#define le64toh(x) OSSwapLittleToHostInt64(x)

#define __BIG_ENDIAN    BIG_ENDIAN
#define __LITTLE_ENDIAN LITTLE_ENDIAN
#define __BYTE_ORDER    BYTE_ORDER
#endif
#endif /* PORTABLE_ENDIAN_H_ */
```
and include that.
```
diff --git a/include/ur_modern_driver/robot_state.h b/include/ur_modern_driver/robot_state.h
index 159974b..445bd11 100644
--- a/include/ur_modern_driver/robot_state.h
+++ b/include/ur_modern_driver/robot_state.h
@@ -26,6 +26,7 @@
 #include <mutex>
 #include <condition_variable>
 #include <netinet/in.h>
+#include "portable_endian.h"

 namespace message_types {
 enum message_type {
diff --git a/include/ur_modern_driver/robot_state_RT.h b/include/ur_modern_driver/robot_state_RT.h
index 1f5b2af..8c3fa8c 100644
--- a/include/ur_modern_driver/robot_state_RT.h
+++ b/include/ur_modern_driver/robot_state_RT.h
@@ -26,6 +26,7 @@
 #include <mutex>
 #include <netinet/in.h>
 #include <condition_variable>
+#include "portable_endian.h"

 class RobotStateRT {
 private:
```

* Mac might have no need for TCP_QUICKACK. So you can comment out all the TCP_QUICKACK.
//XXX setsockopt(pri_sockfd_, IPPROTO_TCP, TCP_QUICKACK, (char *) &flag_, sizeof(int));

* And I think you already changed these lines as others say.
controller_it->type.c_str()); //XXX hardware_interface.c_str());

I just checked that it compiles ok with these changes.

**Comment by keshavchintamani** [comment]
Thanks so much for helping me with this issue @Horagong, now it works!

The only addition error I got was:

/Users/kchintamani/sandbox/roskinetic_ws/universalrobots_ws/src/ur_modern_driver/src/ur_driver.cpp:55:23: error:
      invalid operands to binary expression ('__bind<int &, sockaddr *, unsigned long>' and
      'int')
                        sizeof(serv_addr)) < 0) {

This was fixed by changing
-  bind( 
+ ::bind( 
using: https://stackoverflow.com/questions/16180322/c-xcode-sockets-bind-error

Again many thanks!
