### ISSUE TITLE
Error building: no member named 'hardware_interface'

### ISSUE THREAD

**Issue by atyshka** [ThomasTimm/ur_modern_driver#168]
I attempted to clone and build this repository but ran into errors with hardware_interface, specifically the struct ControllerInfo. I get the error `‘const struct hardware_interface::ControllerInfo’ has no member named ‘hardware_interface’` Sure enough, this string has been missing from the struct since a 2015 commit. I tried two workarounds: using an old version of controller_interface.h in hardware_interface that did have the hardware_interface string, and for the other solution replacing all references to the `hardware_interface` string with the `type` string, which appeared to be unused. Both solutions successfully built, but when I tried to run the bringup they both crash with error saying it could not find robot firmware. Am I missing something? Plenty of others have gotten this driver working fine.

**Comment by gavanderhoorn** [comment]
I'm going to close this, as this is a known issue (see #58 fi).
