### ISSUE TITLE
zero-g mode for UR10

### ISSUE THREAD

**Issue by nazir-ust** [ThomasTimm/ur_modern_driver#171]
I would like to run my UR10 arm in zero-g mode where it can be freely moved by an external force during part of execution. Any suggestions on how this can be done with a running `ur_modern_driver`?

**Comment by gavanderhoorn** [comment]
As this is more a question about how to implement something than an actual issue with the driver, I'm going to close this.

Not sure how much response you'll get, but could you please ask these sort of questions on ROS Answers? We'd like to reserve this issue tracker for bugs and enhancement requests.
