### ISSUE TITLE
How to add calibration.conf data from controller to URDF for maximum accuracy

### ISSUE THREAD

**Issue by tragolf** [ThomasTimm/ur_modern_driver#179]
Hi,
I try to implement the calibration data from the UR-controller to the URDF-File. The goal is to reduce the discrepancy between the position of tool0 in MoveIt and the tool0_controller (2-3mm).
I copied the calibration.conf data from the controller. The content of the file is:
```
[mounting]  
delta_theta = [ 2.07750978653505926e-05, 0.96821571555565844, -1.85685385014877657, 0.888647901450376643, 5.66106814887767484e-05, -7.46310764096455082e-05]
delta_a = [ 0.000393621049984383038, 0.184093300397451837, 0.14493953300732923, -6.43297403642304399e-05, 7.76709040084077299e-06, 0]
delta_d = [ 4.00263097760228392e-05, 278.244144925623573, -183.695513914913732, -94.5471513669751289, 0.000304782681775556119, 0.000123737941387466743]
delta_alpha = [ -0.000271624944216508624, 0.00125856505456124258, -0.00322052070697146503, 0.00065153016530383745, -0.00058700465721117645, 0]
```

The following properties are defined in the URDF-File from ur_description of UR5:

```
<xacro:property name="ur5_d1" value="0.089159" />
<xacro:property name="ur5_a2" value="-0.42500" />
<xacro:property name="ur5_a3" value="-0.39225" />
<xacro:property name="ur5_d4" value="0.10915" />
<xacro:property name="ur5_d5" value="0.09465" />
<xacro:property name="ur5_d6" value="0.0823" />
```

How can I implement the calibration data in the URDF-File? Just adding the delta values to the values from the URDF-File results in crazy numbers.

**Comment by gavanderhoorn** [comment]
I know it is confusing, but the xacro macros are not actually in this repository, but in [universal_robot](https://github.com/ros-industrial/universal_robot).

Could you please repost this there and close this one?
