### ISSUE TITLE
Could you give me your TCP protocol 

### ISSUE THREAD

**Issue by HelloDusty** [ThomasTimm/ur_modern_driver#185]
Hi
I am trying to connect UR to vrep. Thus, I am going to connect to vrep to ur driver by tcp, and then, connect vrep to ROS environment. But, it's hard to read all the code of ur_modern_driver. Could you give me your TCP protocol from ur_modern_driver to UR.
Thanks

**Comment by gavanderhoorn** [comment]
The only protocol we're using is the one created by Universal Robots themselves: see [Remote Control Via TCP/IP - 16496](https://www.universal-robots.com/how-tos-and-faqs/how-to/ur-how-tos/remote-control-via-tcpip-16496/) for the documentation.

But tbh, I don't think what you're trying to do is a good approach. Now what I think doesn't really matter, but I would not try to implement the entire UR TCP protocol just to be able to interface with VREP.

**Comment by gavanderhoorn** [comment]
As there isn't anything really actionable in this ticket (or at least not for the package in this repository), I'm going to close it. Do feel free to keep commenting though.
