### ISSUE TITLE
Can use this with robot movement interface package?

### ISSUE THREAD

**Issue by lakshmip001** [ThomasTimm/ur_modern_driver#196]
For my application , I need to record tool velocity while the ur_driver in the robot movement interface doesnt have topic tool_velocity. Can you please suggest how I can record velocity?

**Comment by gavanderhoorn** [comment]
If you don't command any motion with `ur_modern_driver` then in theory you could start it and it would publish tool velocity without interfering with anything else running on the controller.

I've not used "robot movement interface" though, so I cannot guarantee it will work.

**Comment by gavanderhoorn** [comment]
I'm going to close this as it's not really an issue, but a question about configuration / usage.

@lakshmip001: feel free to keep commenting though.
