### ISSUE TITLE
Action interface sanity check doesn't actually confirm that trajectory start and current postion agree

### ISSUE THREAD

**Issue by hemes** [ThomasTimm/ur_modern_driver#29]
The comments (and technical report) allude to the driver checking new trajectories for sane values however it is currently possible to send trajectories in which the trajectory's start does not agree with the robot's current position.

The issue seems to be with the if check in line [332](https://github.com/ThomasTimm/ur_modern_driver/blob/master/src/ur_ros_wrapper.cpp#L332) of ur_ros_wrapper.cpp

This can be replicated using the URSim with the driver along with RViz MoveIt! plugin with the following steps:
1) launch simulator, ur_modern_driver, and Rviz/MoveIt!
2) drag the goal some significant distance from the initial state and click *Plan*
3) confirm the plan is valid and then click *Execute* (Robot executes plan as expected)
4) without adjusting the goal state click *Plan* again (generates plan from original/initial state)
5) click *Execute* (plan is sent despite differing start positions, resulting in a protective stop in URSim)

-- Note: using *Execute and Plan* seems to use current robot position as the start state instead of the previously set start state via the Query GUI.

**Comment by ThomasTimm** [comment]
I believe this was fixed by your pull request, so I'll close this issue.
