### ISSUE TITLE
[question] About the robot state publisher in launch files...

### ISSUE THREAD

**Issue by carlosjoserg** [ThomasTimm/ur_modern_driver#32]
Is there any reason why the `type="state_publisher"` instead of `type="robot_state_publisher"` is being used [here](https://github.com/ThomasTimm/ur_modern_driver/blob/master/launch/ur_common.launch#L21)?

I'm on indigo, and I get this warning: 
`[ WARN] [1453385917.020716971]: The 'state_publisher' executable is deprecated. Please use 'robot_state_publisher' instead`

**Comment by ThomasTimm** [comment]
Nope, no reason except excessive copy/paste from the old ur_driver launch files :-) 
I have changed it to use the new executable
