### ISSUE TITLE
joint_states.names empty when prefix parameter not found

### ISSUE THREAD

**Issue by jettan** [ThomasTimm/ur_modern_driver#34]
Looking at [ur_ros_wrapper.cpp#L93-L108](https://github.com/ThomasTimm/ur_modern_driver/blob/682c77582b9e9c4052589508c9af33766c4828a2/src/ur_ros_wrapper.cpp#L93-L108), it seems the first if statement is only taken when the `prefix` parameter is found, so when this parameter is not set, no joint names are pushed into the `joint_names` vector.

This is probably caused by the `false` returned by `ros::param::get` in case the parameter is not there.

**Comment by ThomasTimm** [comment]
You are, quite right, thanks for finding this bug.
I will fix it immediately.
