### ISSUE TITLE
Goal start doesn't match current pose

### ISSUE THREAD

**Issue by SARAWIN-BK-7** [ThomasTimm/ur_modern_driver#385]
I'm trying to control ur5 using actionlib but got stuck due to error on teminal "Goal start doesn't match current pose"

**Comment by gavanderhoorn** [comment]
Could you please confirm you've seen [the deprecation notice in the readme](https://github.com/ros-industrial/ur_modern_driver#deprecation-notice)?

For anything which is not a CB2, you should not be using this driver.

Please use [UniversalRobots/Universal_Robots_ROS_Driver](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver) instead.
