### ISSUE TITLE
Mismatch in numbering digital pins between set_io and io_states

### ISSUE THREAD

**Issue by sepjansen** [ThomasTimm/ur_modern_driver#40]
I noticed that the numbering of the digital output pins are different for the /io_states topic and the /set_io service call:

Service /set_io:
pin 0-7: Standard digital out
pin 8-9: Tool digital out
pin 10-17: Configurable digital out

rostopic /io_states:
pin 0-7: Standard digital out
pin 8-15: Configurable digital out
pin 16-17: Tool digital out

This mismatch is particularly annoying in case someone is checking the /io_states topic is feedback whether their service call has succesfully been carried out by UR.

Easiest fix seems to me to change the numbering in the /set_io service callback to use the same numbering as in the /io_states topic. I already have this fix ready.

I realize this may break existing applications because the pin numbers will be re-ordered. Should we still merge the fix?

**Comment by BrettHemes** [comment]
+1

I came across this the other day and it had me scratching my head for a while.  I agree that the numbering should definitely match.

The URScript set_digital_io function that had the tool digital outputs at pins 8-9 is now deprecated and replaced by individual functions each for standard, configurable, and tool, all of which are numbered from zero.

That said I think that the set_io service numbering should be changed to match io_states.  Another option would be to replace/augment the current service by/with individual services for set of IO to mimic the official interface.
