### ISSUE TITLE
Wrong length of message on RT interface

### ISSUE THREAD

**Issue by andreaskoepf** [ThomasTimm/ur_modern_driver#48]
From time to time (if the robot is running for multiple hours) I see log messages like:

```
Wrong length of message on RT interface: 1072623616
Wrong length of message on RT interface: 1072473427
Wrong length of message on RT interface: 1072398338
Wrong length of message on RT interface: 1072323238
Wrong length of message on RT interface: 1072473427
Wrong length of message on RT interface: 1072097960
Wrong length of message on RT interface: 0
```

Is this something to worry about?

I had a look at [ur_communication.cpp](https://github.com/ThomasTimm/ur_modern_driver/blob/0dc244bbe8946f5cd9f1e7d26501aa47e8c285dc/src/ur_communication.cpp#L127-L130):

```
select(sec_sockfd_ + 1, &readfds, NULL, NULL, &timeout);
			bytes_read = read(sec_sockfd_, buf, 2048); // usually only up to 1295 bytes
```

Could it be sometimes more than one message is available, e.g. total data exceeding 2048 bytes and then with the next call a message is read in the middle? Maybe for unknown reasons the UR sends a burst or the thread context switching on the local machine was too slow?

**Comment by sepjansen** [comment]
I also see these messages sometimes.

It happens especially when I'm running the UR simulator at higher speeds, e.g. at frequency of 250 Hz rather than the standard 125 Hz (You can do this only in simulation of course) . That would confirm your suspicions.

I never had any issues with it though.

**Comment by ThomasTimm** [comment]
As noted in #42 this can safely be ignored. Apparently UR broadcast something undocumented on the realtime port from time to time. When I implement official support for firmware 3.2 ( See #17 ) this message will disappear.
