### ISSUE TITLE
Why are the ur_msgs not used in robote_state.h?

### ISSUE THREAD

**Issue by NikolasE** [ThomasTimm/ur_modern_driver#84]
I wonder why all the values of the different packages of the secondary interface are stored in separate variables and only later (in ur_ros_wrapper.cpp) merged into the ur_msgs-Datatypes. Couldn't we directly include the ros-headers, fill the messages, so that the RobotState-class then provides the ros-messages that can then be published directly?

**Comment by ThomasTimm** [comment]
Quite simply to make the driver work standalone. By only having a single (or two files) that interfaces the driver to ROS, it is a lot easier to port the driver to something non-ROS, or to change the driver if/when the ROS architecture changes.
From what I've been told from core ROS 2.0 developers, the preferred way of wrting software to ros is to make your program a stand-alone library, and then just have a top-file that interfaces to ROS.
