### ISSUE TITLE
Using "AND" in C++

### ISSUE THREAD

**Issue by NikolasE** [ThomasTimm/ur_modern_driver#90]
I just found this code
(ur_driver.cpp l. 95)
`while ((inp_timestamps[inp_timestamps.size() - 1]
			>= std::chrono::duration_cast<std::chrono::duration<double>>(t - t0).count())
and executing_traj_) {`

Whatf is the 'and' doing there? And where is it defined? I could not find the corresponding #define or whatever black magic was used to create it.

**Comment by miguelprada** [comment]
Never seen it before either, but apparently it's a [C++ keyword](http://en.cppreference.com/w/cpp/keyword/and), equivalent to `&&`. :no_mouth:

**Comment by NikolasE** [comment]
It's really official C++... Thanks.
